### ISSUE TITLE
Automatically add people to lists when they subscribe via specific forms

### ISSUE THREAD

**Issue by tbaeuerle** [hizzle-co/noptin#540]
**Describe the bug**
When I try to automatically add people to lists when they subscribe via specific forms like described here:
https://noptin.com/guide/email-subscribers/subscriber-lists/
And subscribe via configured form shortcode, my subscribed email does not land in the configured Email-List.

**To Reproduce**
1. Go to 'Subscription Forms' in Noptin menu
2. Click on a form and enter your Email-List in the "Lists"-Context
3. Save configuration
4. Copy forms shortcode
5. Enter shortcode anywhere in frontend
6. Subscribe to list
7. Confirm DOI-Mail by clicking on link
8. Check Subscription in wordpress backend 

**Expected behavior**
I would expect that my subscription is automatically added to the email-list configured in the form settings. I did exactly what is described in the guide (see link above).

**Screenshots**
Here i configured the subscription form:
![image](https://user-images.githubusercontent.com/51750954/213185283-9fc71e79-66cf-469f-b523-4214b8c7405e.png)

After subscription i see following overview on my subscriber list. The subscriber was not added to my configured email list:
![image](https://user-images.githubusercontent.com/51750954/213185905-251d57c8-6ffd-447d-a21c-79b6ead491ba.png)

The selected list is set to public:
![image](https://user-images.githubusercontent.com/51750954/213186425-5949422a-a064-4d71-a47f-0fc2cf84f07d.png)

**Desktop:**
 - OS: Windows 11
 - Browser Google Chrome (latest)
 - We have a **Automate (Lifetime)** License Key activated on our page with active Ultimate Addons Pack

**Comment by picocodes** [comment]
Just checked and indeed subscribers are not added to lists if double opt-in is enabled. This has been fixed. We'll release an update tomorrow after we've done further tests.

**Comment by tbaeuerle** [comment]
@picocodes Thanks for your reply.
I updated noptin plugin today to get these fixes, but still have the same issues. Is the bugfix already included in version "1.11.0" ?

**Comment by picocodes** [comment]
Yes, update both Noptin and the Ultimate Addons Pack.

**Comment by picocodes** [comment]
Remember to clear your cache just in case
